### ISSUE TITLE
Cambiar secrets por variables

### ISSUE THREAD

**Issue by fernandomdiaz-exxom** [mepbust/docker-test#5]
Podes poner una seccion env

env:
  OPENSHIFT_DC_DEV : "docker-test-git"
  OPENSHIFT_NAMESPACE : "hello-world-test-np"
   

--request POST -H "Authorization: Bearer ${{ secrets.OCSATOKEN }}" --data '{"kind":"DeploymentRequest","apiVersion":"apps.openshift.io/v1","name":"${{ secrets.OPENSHIFT_DC_DEV }}","latest":true,"force":true}' \
#        https://api.aro.kepler.xom.cloud:6443/apis/apps.openshift.io/v1/namespaces/${{ env.OPENSHIFT_NAMESPACE }}/deploymentconfigs/${{ env.OPENSHIFT_DC_DEV }}/instantiate

Tambien podes pasar el nombre de la imagen como variable de pipeline. Porque todos estos no es necesario que sean secrets
Acordate de probar con el token de la service account de deploy, sino creamos una service account con kepler-admin

**Comment by mepbust** [comment]
done
